### ISSUE TITLE
Warning on vite config

### ISSUE THREAD

**Issue by hi-reeve** [wheatjs/vite-plugin-vue-type-imports#1]
hello , first of all thankyou for this amazing and life saver plugin
i got a warning when trying to use the plugin on vite config

![image](https://user-images.githubusercontent.com/45350572/139611665-bcbd6bdd-9a03-44c8-af34-4a202c14d5b8.png)

**Comment by didavid61202** [comment]
same +1

**Comment by wheatjs** [comment]
Should be fixed in version 0.0.2
