### ISSUE TITLE
use withDefaults error

### ISSUE THREAD

**Issue by P-Mz** [wheatjs/vite-plugin-vue-type-imports#11]
![image](https://user-images.githubusercontent.com/40508526/151128095-9ca0ae35-190a-4cba-a6a5-75495fdcff99.png)

https://stackblitz.com/edit/vitejs-vite-9mc6hi?file=src%2Fcomponents%2FHelloWorld.vue

**Comment by Zolyn** [comment]
The plugin does not replace imported variables, which is not its job. You will get the same error even if you disable this plugin. ~~I think this should be a feature request.~~

**Comment by Zolyn** [comment]
You can just change `defaultProps` to `{ ...defaultProps }` to force Vue to fallback to runtime merging

Otherwise, you can install a plugin to do this automatically for you.

[vite-plugin-vue-with-defaults-imports](https://github.com/Zolyn/vite-plugin-vue-with-defaults-imports)
