### ISSUE TITLE
Bug with isCustomElement nuxt 3

### ISSUE THREAD

**Issue by Archetipo95** [wheatjs/vite-plugin-vue-type-imports#14]
Hi guys, I noticed that I get a weird behaviour when I use this module in nuxt 3 and vidstack video player lib. I made 2 blitzstack examples one working without vite-plugin-vue-type-imports and one broken with vite-plugin-vue-type-imports. The only way I found to force it to work with ur module is to move the imports from ThePlayer.vue in app.vue.

Working: https://stackblitz.com/edit/github-4bboop
Broken: https://stackblitz.com/edit/github-4bboop-qntiz3

If I can help in someway with more info tell me and I will try to provide them.

**Comment by Zolyn** [comment]
It should be fixed in [v0.2.0](https://github.com/wheatjs/vite-plugin-vue-type-imports/releases/tag/v0.2.0)
