### ISSUE TITLE
CAN NOT import types from entry file with multiple exports levels

### ISSUE THREAD

**Issue by gaokun** [wheatjs/vite-plugin-vue-type-imports#17]
The code below is not working:

#### Vue
```js
import type { MsgProps } from './types' 

defineProps<MsgProps>()
```

#### types.ts
```js
export * from './msg'
```

#### msg.ts
```js
export interface MsgProps {
  msg: string;
}
```

I got:
> [@vue/compiler-sfc] type argument passed to defineProps() must be a literal type, or a reference to an interface or literal type

If I `import type { MsgProps } from './msg' `, it works ok.

#### Reproduce Repo
https://github.com/gaokun/vue3-ts-vite-type-imports

**Comment by Zolyn** [comment]
>The following syntaxes are not supported currently:
>  - `import default`
>  - `import { a as b }`
>  - `export default`
>  - `export * from`

See [Known limitations](https://github.com/Zolyn/vite-plugin-vue-type-imports/tree/dev-1#known-limitations)

This is a known issue, however, the documentation is currently not updated until #15 is merged.

Unfortunenately, this may take a while to fix because I'm not focusing on this project now.

**Comment by gaokun** [comment]
@Zolyn 
Many thanks for your extremely quick response.
And thanks to your work anyway.

**Comment by Zolyn** [comment]
Supported in [v0.2.2](https://github.com/wheatjs/vite-plugin-vue-type-imports/releases/tag/v0.2.2)
