### ISSUE TITLE
Cannot use namespace 'xxx' as a type.ts(2709)

### ISSUE THREAD

**Issue by wangrongding** [wheatjs/vite-plugin-vue-type-imports#18]
Hi, I'm having this problem, it doesn't seem to be caused by your plugin, but I don't know how to fix it, can you take a look?  

Thanks~

Cannot use namespace 'xxx' as a type.ts(2709)
<img width="585" alt="image" src="https://user-images.githubusercontent.com/42437658/181729997-aca8c450-12a2-43bc-a912-44ad7a8e6c44.png">

https://github.dev/wangrongding/vue-super-admin/blob/main/src/page/testing/test.vue#L6

**Comment by Zolyn** [comment]
It may be related to your typescript version, check if it is the latest version by runnning `npm list`.

**Comment by wangrongding** [comment]
I feel that it should not be a problem of version, see other people's version of typescript is much lower than my version did not appear this error

<img width="735" alt="image" src="https://user-images.githubusercontent.com/42437658/181757741-4c053cc7-06e2-4b89-ba1a-e4893775ba0b.png">

Documents with the error message：
https://github.dev/wangrongding/vue-super-admin/blob/main/src/page/testing/test.vue#L6

My version of typescript：
https://github.dev/wangrongding/vue-super-admin/blob/main/package.json#L69

**Comment by Zolyn** [comment]
I think you can try removing `.ts`
```typescript
import type { Test } from './type'
```

**Comment by Zolyn** [comment]
Alternatively, you can do this if you want to preserve extensions:
```typescript
// shims-vue.d.ts
declare module '*.ts' {
  export { Test } from '@/page/testing/type'
}
```
Also, I've noticed that you declare it in multiple files. (`@/env.d.ts`, `@/types/shims-vue.d.ts`) I think you should remove the redundant declaration.

**Comment by wangrongding** [comment]
Thanks, good brother.
Have a great life.🥰
