### ISSUE TITLE
Type nesting is not imported

### ISSUE THREAD

**Issue by sxzz** [wheatjs/vite-plugin-vue-type-imports#3]
```ts
// types.ts
type A = string
export interface Props {
  val?: string
  a: A
}
```

```vue
<script setup lang="ts">
// Test.vue
import type { Props } from './types'
defineProps<Props>()
</script>
```

And it transformed to 
```ts
import { defineComponent as _defineComponent } from "vue";
const _sfc_main = /* @__PURE__ */ _defineComponent({
  props: {
    val: { type: String, required: false },
    a: { type: null, required: true } // ⚠️ type of `a` is null
  },
  setup(__props, { expose }) {
    expose();
    const __returned__ = {};
    Object.defineProperty(__returned__, "__isScriptSetup", { enumerable: false, value: true });
    return __returned__;
  }
});
_sfc_main.__hmrId = "07bdddea";
typeof __VUE_HMR_RUNTIME__ !== "undefined" && __VUE_HMR_RUNTIME__.createRecord(_sfc_main.__hmrId, _sfc_main);
import.meta.hot.accept(({ default: updated, _rerender_only }) => {
  if (_rerender_only) {
    __VUE_HMR_RUNTIME__.rerender(updated.__hmrId, updated.render);
  } else {
    __VUE_HMR_RUNTIME__.reload(updated.__hmrId, updated);
  }
});
import _export_sfc from "plugin-vue:export-helper";
export default /* @__PURE__ */ _export_sfc(_sfc_main, [["__file", "/Users/kevin/Developer/repos/element-plus/play/src/Test.vue"]]);
```

<img width="818" alt="Screen Shot 2021-12-02 at 08 16 23" src="https://user-images.githubusercontent.com/6481596/144334837-972d31d9-855e-41b5-83be-c9bb76a390c0.png">

<img width="1024" alt="Screen Shot 2021-12-02 at 08 16 44" src="https://user-images.githubusercontent.com/6481596/144334854-5b07d2b7-e5e1-40dc-a424-b7716b33042f.png">

**Comment by wheatjs** [comment]
Thanks for the report, I'll see if I can get a fix out this weekend

**Comment by g191091788** [comment]
Please support namespace!
thanks!

```ts
export namespace Params {
  export interface User {
    name: string;
    pwd: string;
  }
}
```

**Comment by wheatjs** [comment]
@g191091788 I haven't used namespace in the past, can you show me how you would be using it in the vue file so I know how to support it

**Comment by g191091788** [comment]
@wheatjs 
[example](https://codesandbox.io/s/k341f?file=/src/components/HelloWorld.vue)

**Comment by wheatjs** [comment]
Thanks!

**Comment by wheatjs** [comment]
Type nesting should work now, trying installing the latest version

**Comment by wheatjs** [comment]
@g191091788 It seems like the official Vue library doesn't support namespaces like they do interfaces or types. I'd suggest raising an issue with Vue first. If they decide to support it there, I'll add support for it to this plugin as well

**Comment by sxzz** [comment]
OK. Thanks!
