### ISSUE TITLE
Nuxt 3 remove warnings `Cannot find type` for TypeScript build-in types like Array, Error, Record

### ISSUE THREAD

**Issue by mrauhu** [wheatjs/vite-plugin-vue-type-imports#34]
Hello @wheatjs.

Mention of same behavior: https://github.com/wheatjs/vite-plugin-vue-type-imports/issues/32.
Source of bug: https://github.com/wheatjs/vite-plugin-vue-type-imports/pull/22.

After update this package to the latest version ([`0.2.2`](https://github.com/wheatjs/vite-plugin-vue-type-imports/compare/v0.2.0...v0.2.2)) got warnings about TypeScript build-in types, like:

```
 WARN  [vite-plugin-vue-type-imports] WARN: Cannot find type: Error 
 WARN  [vite-plugin-vue-type-imports] WARN: Cannot find type: Array
 WARN  [vite-plugin-vue-type-imports] WARN: Cannot find type: Record
```

![image](https://user-images.githubusercontent.com/2821574/190536698-651828e0-d4ae-4ff9-8473-8d8a5bde059d.png)

Is there a way to remove warnings?

Best wishes,
Sergey.

**Comment by Zolyn** [comment]
It seems to be noisy, I will move it to debug level in the next release.

**Comment by Zolyn** [comment]
Try [v0.2.3](https://github.com/wheatjs/vite-plugin-vue-type-imports/releases/tag/v0.2.3)

**Comment by mrauhu** [comment]
Thank you.
