### ISSUE TITLE
Sourcemaps generation

### ISSUE THREAD

**Issue by r9mp** [wheatjs/vite-plugin-vue-type-imports#37]
Hi

Following the issue nuxt/framework#36 .

It seems that the current state of vite-plugin-vue-type-imports does not generate sourcemaps.

I tryed to make this plugin work with Vitest & Nuxt 3 and found two problems:
- The following error message is displayed many times: "Sourcemap is likely to be incorrect: a plugin (vite-plugin-vue-type-imports) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help".
- After applying `vitest --run`, the process does not stop anymore once done ; and it seems that the process is executed twice (or there is something weird... but don't really know what).

You can find a repo to reproduce it here: https://github.com/r9mp/vitest-nuxt

The problem only occurs on the file test/nuxt.spec.ts and when the setup function is called. If you comment it, the problems stop.

To reproduce, just clone the repo `git clone https://github.com/r9mp/vitest-nuxt`, then `yarn install`, and `yarn test` to launch the tests in verbose mode.

R

**Comment by Zolyn** [comment]
>After applying vitest --run, the process does not stop anymore once done ; and it seems that the process is executed twice (or there is something weird... but don't really know what).

I can't reproduce.

**Comment by r9mp** [comment]
I deleted node_modules/, yarn install, yarn test, and same result. I'm on Windows 10, the error is the following:

![image](https://user-images.githubusercontent.com/12933109/193315182-da9f832b-16a5-4476-9b5c-265dbddef896.png)

![image](https://user-images.githubusercontent.com/12933109/193314780-5617499d-dcda-4455-843f-725ca6efc057.png)

On which OS are you? I can try to reproduce on Ubuntu if you want.

**Comment by Zolyn** [comment]
I can reproduce it on Windows 11, but not on Arch Linux.

Seems to be an upstream bug. See https://github.com/nuxt/nuxt.js/issues/15065

**Comment by Zolyn** [comment]
I cloned https://github.com/manniL/nuxt-test-utils-vitest-windows and removed the call of `useTextContext`. The problem still exists, so I think it's an upstream bug.

**Comment by Zolyn** [comment]
Sourcemaps generation is now supported in [v0.2.3](https://github.com/wheatjs/vite-plugin-vue-type-imports/releases/tag/v0.2.3)

**Comment by r9mp** [comment]
Works for me! Thanks a lot @Zolyn !
