### ISSUE TITLE
Support for Vue 2.7

### ISSUE THREAD

**Issue by y-a-ava** [wheatjs/vite-plugin-vue-type-imports#39]
the peer dependencies for this plugin are:
 "@vue/compiler-sfc": "^3.2.24",
 "vue": "^3.2.24"

i tested it with vue 2.7 using npm i --force, and it works as expected.
any reason for not supporting it?

**Comment by Zolyn** [comment]
Try [0.2.4](https://github.com/wheatjs/vite-plugin-vue-type-imports/releases/tag/v0.2.4)

**Comment by y-a-ava** [comment]
> Try [0.2.4](https://github.com/wheatjs/vite-plugin-vue-type-imports/releases/tag/v0.2.4)

working! thanks a lot for the speedy response and release!
