### ISSUE TITLE
type argument passed to defineProps() must be a literal type, or a reference to an interface or literal type.

### ISSUE THREAD

**Issue by laterdays** [wheatjs/vite-plugin-vue-type-imports#41]
[vite] Internal server error: [@vue/compiler-sfc] type argument passed 
to defineProps() must be a literal type, or a reference to an interface or liter
al type.

```
import type { ButtonProps } from 'naive-ui';
defineProps<ButtonProps>();
```

**Comment by Zolyn** [comment]
Can you provide a reproduction link or repo?

**Comment by Zolyn** [comment]
https://antfu.me/posts/why-reproductions-are-required
