### ISSUE TITLE
Error when building with vite-plugins-dts

### ISSUE THREAD

**Issue by ivanmaxlogiudice** [wheatjs/vite-plugin-vue-type-imports#51]
I have some errors when building with type imports

![image](https://user-images.githubusercontent.com/3275920/216703014-22089166-ed0c-4cc8-a046-84648cb3c486.png)
### Steps to reproduce

- `git clone -b type-imports https://github.com/ivanmaxlogiudice/ui.git`
- Run `pnpm install` followed by `pnpm build`

### System Info

```
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 4.53 GB / 15.87 GB
  Binaries:
    Node: 18.13.0 - C:\laragon\bin\nodejs\node-v18.13.0-win-x64\node.EXE
    Yarn: 1.22.19 - C:\laragon\bin\yarn\bin\yarn.CMD
    npm: 8.19.3 - C:\laragon\bin\nodejs\node-v18.13.0-win-x64\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.69)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @types/node: ^18.11.18 => 18.11.18
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0
    class-variance-authority: ^0.4.0 => 0.4.0
    typescript: ^4.9.5 => 4.9.5
    vite: ^4.1.1 => 4.1.1
    vite-plugin-dts: ^1.7.2 => 1.7.2
    vite-plugin-vue-type-imports: ^0.2.4 => 0.2.4
    vue: ^3.2.47 => 3.2.47
    vue-tsc: ^1.0.24 => 1.0.24
```

**Comment by selemondev** [comment]
Hey there @ivanmaxlogiudice 👋, I also encountered the same problem but I found some sort of solution for it. You can install the `rollup-plugin-typescript2`  plugin as shown in the [documentation](https://www.npmjs.com/package/rollup-plugin-typescript2) and use it in your `vite.config.ts` file as shown below : 

[Check it out here](https://ray.so/#code=CmltcG9ydCB7IGZpbGVVUkxUb1BhdGgsIFVSTCB9IGZyb20gIm5vZGU6dXJsIjsKaW1wb3J0IHsgcmVzb2x2ZSB9IGZyb20gInBhdGgiOwoKaW1wb3J0IHsgZGVmaW5lQ29uZmlnIH0gZnJvbSAidml0ZSI7CmltcG9ydCB2dWUgZnJvbSAiQHZpdGVqcy9wbHVnaW4tdnVlIjsKaW1wb3J0IFZ1ZVR5cGVJbXBvcnRzIGZyb20gInZpdGUtcGx1Z2luLXZ1ZS10eXBlLWltcG9ydHMiOwppbXBvcnQgdHlwZXNjcmlwdDIgZnJvbSAicm9sbHVwLXBsdWdpbi10eXBlc2NyaXB0MiIKLy8gaHR0cHM6Ly92aXRlanMuZGV2L2NvbmZpZy8KZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29uZmlnKHsKICAgIGJ1aWxkOiB7CiAgICAgICAgbGliOiB7CiAgICAgICAgICAgIC8vIENvdWxkIGFsc28gYmUgYSBkaWN0aW9uYXJ5IG9yIGFycmF5IG9mIG11bHRpcGxlIGVudHJ5IHBvaW50cwogICAgICAgICAgICBlbnRyeTogcmVzb2x2ZShfX2Rpcm5hbWUsICJzcmMvaW5kZXgudHMiKSwKICAgICAgICAgICAgbmFtZTogIm15LWxpYnJhcnktbmFtZSIsCiAgICAgICAgICAgIC8vIHRoZSBwcm9wZXIgZXh0ZW5zaW9ucyB3aWxsIGJlIGFkZGVkCiAgICAgICAgICAgIGZpbGVOYW1lOiAoZm9ybWF0KSA9PiBgbXktbGlicmFyeS1uYW1lLiR7Zm9ybWF0fS5qc2AsCiAgICAgICAgfSwKICAgICAgICByb2xsdXBPcHRpb25zOiB7CiAgICAgICAgICAgIC8vIG1ha2Ugc3VyZSB0byBleHRlcm5hbGl6ZSBkZXBzIHRoYXQgc2hvdWxkbid0IGJlIGJ1bmRsZWQKICAgICAgICAgICAgLy8gaW50byB5b3VyIGxpYnJhcnkKICAgICAgICAgICAgZXh0ZXJuYWw6IFsidnVlIl0sCiAgICAgICAgICAgIG91dHB1dDogewogICAgICAgICAgICAgICAgLy8gUHJvdmlkZSBnbG9iYWwgdmFyaWFibGVzIHRvIHVzZSBpbiB0aGUgVU1EIGJ1aWxkCiAgICAgICAgICAgICAgICAvLyBmb3IgZXh0ZXJuYWxpemVkIGRlcHMKICAgICAgICAgICAgICAgIGdsb2JhbHM6IHsKICAgICAgICAgICAgICAgICAgICB2dWU6ICJWdWUiLAogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgfSwKICAgICAgICB9LAogICAgfSwKICAgIHBsdWdpbnM6IFt2dWUoKSwgVnVlVHlwZUltcG9ydHMoKSwgdHlwZXNjcmlwdDIoewogICAgICAgIGNoZWNrOiBmYWxzZSwKICAgICAgICBpbmNsdWRlOiBbInNyYy9jb21wb25lbnRzLyoqLyoudnVlIiwgJ3NyYy9pbmRleC50cyddLAogICAgICAgIHRzY29uZmlnT3ZlcnJpZGU6IHsKICAgICAgICAgICAgY29tcGlsZXJPcHRpb25zOiB7CiAgICAgICAgICAgICAgICBvdXREaXI6ICJkaXN0IiwKICAgICAgICAgICAgICAgIHNvdXJjZU1hcDogdHJ1ZSwKICAgICAgICAgICAgICAgIGRlY2xhcmF0aW9uOiB0cnVlLAogICAgICAgICAgICAgICAgZGVjbGFyYXRpb25NYXA6IHRydWUsCiAgICAgICAgICAgIH0sCiAgICAgICAgfSwKICAgICAgICBleGNsdWRlOiBbInZpdGUuY29uZmlnLnRzIl0KICAgIH0pXSwKICAgIHJlc29sdmU6IHsKICAgICAgICBhbGlhczogewogICAgICAgICAgICAiQCI6IGZpbGVVUkxUb1BhdGgobmV3IFVSTCgiLi9zcmMiLCBpbXBvcnQubWV0YS51cmwpKSwKICAgICAgICB9LAogICAgfSwKfSk7&title=vite.config.ts&language=typescript)

Let me know if this works for you. Cheers 🥂
