### ISSUE TITLE
Parsing ast occur null pointer

### ISSUE THREAD

**Issue by cizkey** [wheatjs/vite-plugin-vue-type-imports#7]
![image](https://user-images.githubusercontent.com/14026236/145669006-44214b17-8499-4b6f-8055-7b50c59cc790.png)

```
 [vite] Internal server error: Cannot read property 'value' of null
  Plugin: vite-plugin-vue-type-imports
```

I checked the error code as follows:

![image](https://user-images.githubusercontent.com/14026236/145669051-ca284966-71dc-43a3-a5dc-65a2b55e5969.png)

and At the same time, compiler-sfc occur error 
```
[vite] Internal server error: [@vue/compiler-sfc] type argument passed to defineProps() must bence to an interface or literal type.
```

Are there any other notice in use?  Thank you !

* used version:
vue:  3.2.24
vite: 2.7.1
vite-plugin-vue-type-imports: 0.1.2

**Comment by wheatjs** [comment]
Can you show me the vue file and the file you were trying to import?

**Comment by cizkey** [comment]
it was a mistake,  maybe other error caused. i remove node_modules a few times, this error no longer occur.

**Comment by cizkey** [comment]
> it was a mistake, maybe other error caused. i remove node_modules a few times, this error no longer occur.

see [#9](https://github.com/wheatjs/vite-plugin-vue-type-imports/issues/9)
