### ISSUE TITLE
Can't support default index.ts file

### ISSUE THREAD

**Issue by cizkey** [wheatjs/vite-plugin-vue-type-imports#8]
i use it in simple demo, it working fine, but when i used in my project, it still occured an error.

i write an reproduce demo:  
https://stackblitz.com/edit/vitejs-vite-7gvmeo?file=src%2Fcomponents%2Fcontext-menu%2FMenuItem.vue

the error msg as follow:
![image](https://user-images.githubusercontent.com/14026236/145746354-3652d2c4-f5b6-422b-8025-c2cd533258cc.png)

i have no idea that what caused,  really need your help, thanks.

**Comment by cizkey** [comment]
i found that the error is occur because Plugin can not recognize the `index.ts`

like this:
```js
import { IMenuItem } from '../typings'
```
In fact the interface `IMenuItem` defined in `/typings/index.ts`, 

![image](https://user-images.githubusercontent.com/14026236/145753242-932584bf-7a28-4cf7-b5ca-0f7ed27b1b23.png)

when i use below import code ,  it working fine. 
```
import { IMenuItem } from '../typings/index`
````

![image](https://user-images.githubusercontent.com/14026236/145753420-9a05608d-5f4f-4aa7-a820-f04a10105479.png)

it seems Plugin can not figure out default `index.ts` in directory, or a file has no extensions. 

Will you support this feature ?

**Comment by wheatjs** [comment]
Fixed in latest release, thanks!
